In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 0.24.2
Uninstalling scikit-learn-0.24.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-0.24.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-f7e03b3e.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.24.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-learn==0.24.2
  Using cached scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (3.1.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.21.6)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.4.1)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
Successfully installed scikit-learn-0.24.2

##Preprocesamiento - Data

##Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id 1s9jAV8BDz3eUo8sV9R0pmXEQbTurf-gd

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Entel")
data.head(5)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Reclamos,Bajas,Consultas,Altas
0,1,9,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.631699,0.715072,0.656096,0.808229
1,1,10,2.166667,9807.0,0.000221,16910.0,84763.0,0.199497,21615.0,644556.0,0.033535,0.410101,0.468876,0.448331,0.527333
2,1,11,3.566667,9292.5,0.000384,16863.0,86335.0,0.195321,30124.0,539400.0,0.055847,0.377196,0.437500,0.438256,0.623783
3,1,12,3.500000,9526.5,0.000367,11868.0,74383.0,0.159553,21069.0,582133.0,0.036193,0.448555,0.541643,0.548162,0.750687
4,1,1,16.183333,9680.5,0.001672,10389.0,72254.0,0.143784,19867.0,492719.0,0.040321,0.468233,0.515502,0.563666,0.762664

In [ ]:
#IMPUTACION
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=5)
imputed = imputer.fit_transform(data)
df_imputed = pd.DataFrame(imputed, columns=data.columns)
data = df_imputed
data

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Reclamos,Bajas,Consultas,Altas
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.631699,0.715072,0.656096,0.808229
1,1.0,10.0,2.166667,9807.0,0.000221,16910.0,84763.0,0.199497,21615.0,644556.0,0.033535,0.410101,0.468876,0.448331,0.527333
2,1.0,11.0,3.566667,9292.5,0.000384,16863.0,86335.0,0.195321,30124.0,539400.0,0.055847,0.377196,0.437500,0.438256,0.623783
3,1.0,12.0,3.500000,9526.5,0.000367,11868.0,74383.0,0.159553,21069.0,582133.0,0.036193,0.448555,0.541643,0.548162,0.750687
4,1.0,1.0,16.183333,9680.5,0.001672,10389.0,72254.0,0.143784,19867.0,492719.0,0.040321,0.468233,0.515502,0.563666,0.762664
5,1.0,2.0,29.716667,8998.0,0.003303,8932.0,67143.0,0.133030,15546.0,607591.0,0.025586,0.459780,0.464623,0.568765,0.791793
6,1.0,3.0,1.233333,9868.0,0.000125,9517.0,73596.0,0.129314,15617.0,673615.0,0.023184,0.479005,0.478818,0.553953,0.792965
7,1.0,4.0,0.000000,9767.0,0.000000,9495.0,73652.0,0.128917,14123.0,652977.0,0.021629,0.465691,0.517429,0.505489,0.819660
8,1.0,5.0,0.000000,9485.0,0.000000,8980.0,78846.0,0.113893,14074.0,643427.0,0.021873,0.502797,0.530924,0.545836,0.814852
9,1.0,6.0,5.650000,9473.5,0.000596,7686.0,81675.0,0.094105,13363.0,600422.0,0.022256,0.534981,0.510960,0.573241,0.828891
10,1.0,7.0,13.550000,9473.5,0.001430,7357.0,90069.0,0.081682,17830.0,627107.0,0.028432,0.615804,0.620986,0.631460,0.821570
11,1.0,8.0,13.200000,11079.5,0.001191,8739.0,110115.0,0.079362,11143.0,705167.0,0.015802,0.563170,0.557408,0.579453,0.802263
12,2.0,9.0,3.650000,11195.0,0.000398,9439.0,106450.0,0.088671,9366.0,728733.0,0.012852,0.495330,0.496501,0.563044,0.802889
13,2.0,10.0,25.566667,11151.5,0.002412,10538.0,112293.0,0.093844,8691.0,833348.0,0.010429,0.543193,0.539575,0.580417,0.791845
14,2.0,11.0,26.200000,10883.5,0.003162,10733.0,123951.0,0.086591,8254.0,824329.0,0.010013,0.529268,0.519534,0.573255,0.788873
15,2.0,12.0,3.650000,11195.0,0.000398,9318.0,105572.0,0.088262,9366.0,728733.0,0.012852,0.495330,0.496501,0.563044,0.802889
16,2.0,1.0,8.550000,10926.0,0.000982,10255.0,112705.0,0.090990,15096.0,753705.0,0.020029,0.555169,0.577301,0.604215,0.784874
17,2.0,2.0,2.450000,11048.5,0.000274,8519.0,116685.0,0.073009,21807.0,711570.0,0.030646,0.554207,0.587491,0.601625,0.783871
18,2.0,3.0,2.916667,11933.5,0.000309,7650.0,123288.0,0.062050,20742.0,743322.0,0.027904,0.627927,0.613716,0.657771,0.865575
19,2.0,4.0,7.200000,11327.5,0.000803,10098.0,137363.0,0.073513,21980.0,724338.0,0.030345,0.589407,0.568993,0.622653,0.820420
20,2.0,5.0,8.450000,11651.0,0.000836,9935.0,144857.0,0.068585,31627.0,749060.0,0.042222,0.601727,0.541234,0.620197,0.838996
21,2.0,6.0,18.650000,11208.5,0.001769,8566.0,136845.0,0.062596,26225.0,717125.0,0.036570,0.582836,0.551136,0.655491,0.855585
22,2.0,7.0,0.283333,10922.5,0.000032,9226.0,137435.0,0.067130,27721.0,750059.0,0.036958,0.568421,0.522046,0.595398,0.836158
23,2.0,8.0,7.766667,11651.0,0.000804,11983.0,164667.0,0.072771,31008.0,863904.0,0.035893,0.547166,0.476125,0.581253,0.812659
24,3.0,9.0,6.316667,11651.0,0.000542,5198.0,175787.0,0.029570,26224.0,829122.0,0.031629,0.634547,0.553491,0.669473,0.854301
25,3.0,10.0,1.740000,11651.0,0.000149,3104.0,155053.0,0.020019,22771.0,787734.0,0.028907,0.716680,0.666408,0.746599,0.870173
26,3.0,11.0,8.316667,11495.0,0.000724,2717.0,157561.0,0.017244,23676.0,801422.0,0.029542,0.787015,0.783848,0.815351,0.882432
27,3.0,12.0,0.000000,11783.0,0.000000,3897.0,173154.0,0.022506,25426.0,855474.0,0.029722,0.720719,0.722326,0.746339,0.843995
28,3.0,1.0,3.030000,11647.0,0.000260,3601.0,181251.0,0.019867,27354.0,846245.0,0.032324,0.733620,0.720971,0.760398,0.828831
29,3.0,2.0,2.866667,11937.5,0.000240,3162.0,178552.0,0.017709,25198.0,779991.0,0.032306,0.832352,0.732130,0.790221,0.735316
30,3.0,3.0,33.700000,11937.5,0.002823,3254.0,182871.0,0.017794,32364.0,841070.0,0.038480,0.758600,0.745641,0.810106,0.859791
31,3.0,4.0,2.666667,11937.5,0.000223,3222.0,168281.0,0.019147,38391.0,785477.0,0.048876,0.773094,0.758017,0.796854,0.845038
32,3.0,5.0,3.683333,11937.5,0.000309,3857.0,197825.0,0.019497,31179.0,889714.0,0.035044,0.761682,0.734771,0.800525,0.854405
33,3.0,6.0,1.580000,11937.5,0.000133,3615.0,180645.0,0.020012,28243.0,831701.0,0.033958,0.752563,0.711588,0.819931,0.899706
34,3.0,7.0,0.000000,11937.5,0.000000,5232.0,190318.0,0.027491,29615.0,881653.0,0.033590,0.693252,0.738069,0.750595,0.847228
35,3.0,8.0,3.016667,11647.0,0.000259,5216.0,194235.0,0.026854,29123.0,920062.0,0.031653,0.767544,0.826540,0.791159,0.835480
36,4.0,9.0,2.933333,11340.5,0.000259,3953.0,183241.0,0.021573,30117.0,833695.0,0.036125,0.820102,0.812386,0.849048,0.884192
37,4.0,10.0,8.974667,11457.8,0.000817,5102.0,156787.0,0.036450,22295.8,817064.2,0.027326,0.700307,0.671142,0.732178,0.856589
38,4.0,11.0,7.251333,11344.8,0.000807,5208.8,159650.2,0.035205,22102.4,848420.4,0.025882,0.700631,0.687472,0.730190,0.849968
39,4.0,12.0,0.000000,10911.5,0.000000,5593.0,188532.0,0.029666,30385.0,973143.0,0.031224,0.749471,0.745242,0.769407,0.864368
40,4.0,1.0,0.000000,11647.0,0.000000,4117.0,190757.0,0.021582,25891.0,867100.0,0.029859,0.794816,0.790859,0.814338,0.886270
41,4.0,2.0,1.183333,7796.0,0.000152,4023.0,172367.0,0.023340,24915.0,779504.0,0.031963,0.775907,0.768500,0.804085,0.880270
42,4.0,3.0,0.000000,8143.5,0.000000,3487.0,178672.0,0.019516,23563.0,808844.0,0.029132,0.811104,0.813583,0.824838,0.866770
43,4.0,4.0,0.783333,7948.0,0.000152,3564.0,177067.0,0.020128,15292.0,780906.0,0.019582,0.758904,0.744084,0.794145,0.844356

In [ ]:
data["Reclamos"]

0     0.631699
1     0.410101
2     0.377196
3     0.448555
4     0.468233
5     0.459780
6     0.479005
7     0.465691
8     0.502797
9     0.534981
10    0.615804
11    0.563170
12    0.495330
13    0.543193
14    0.529268
15    0.495330
16    0.555169
17    0.554207
18    0.627927
19    0.589407
20    0.601727
21    0.582836
22    0.568421
23    0.547166
24    0.634547
25    0.716680
26    0.787015
27    0.720719
28    0.733620
29    0.832352
30    0.758600
31    0.773094
32    0.761682
33    0.752563
34    0.693252
35    0.767544
36    0.820102
37    0.700307
38    0.700631
39    0.749471
40    0.794816
41    0.775907
42    0.811104
43    0.758904
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

   Reclamos Reclamos-Cat
0  0.631699            4
1  0.410101            3
2  0.377196            2
3  0.448555            3
4  0.468233            3

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas,Reclamos-Cat
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.715072,0.656096,0.808229,4
1,1.0,10.0,2.166667,9807.0,0.000221,16910.0,84763.0,0.199497,21615.0,644556.0,0.033535,0.468876,0.448331,0.527333,3
2,1.0,11.0,3.566667,9292.5,0.000384,16863.0,86335.0,0.195321,30124.0,539400.0,0.055847,0.437500,0.438256,0.623783,2
3,1.0,12.0,3.500000,9526.5,0.000367,11868.0,74383.0,0.159553,21069.0,582133.0,0.036193,0.541643,0.548162,0.750687,3
4,1.0,1.0,16.183333,9680.5,0.001672,10389.0,72254.0,0.143784,19867.0,492719.0,0.040321,0.515502,0.563666,0.762664,3

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     1
3    19
4    21
5     3
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.715072,0.656096,0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [3 1]]
Precisión del modelo: 0.8125
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.625
Puntaje F1 del modelo: 0.5846153846153846
Curva ROC - AUC del modelo: 0.625

##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.715072,0.656096,0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [3 1]]
Precisión del modelo: 0.8125
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.625
Puntaje F1 del modelo: 0.5846153846153846
Curva ROC - AUC del modelo: 0.625

##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.715072,0.656096,0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [3 1]]
Precisión del modelo: 0.8125
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.625
Puntaje F1 del modelo: 0.5846153846153846
Curva ROC - AUC del modelo: 0.625

##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,6.433333,9429.0,0.000682,4989.0,51894.0,0.096138,50182.0,338717.0,0.148153,0.715072,0.656096,0.808229

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[5 0]
 [3 1]]
Precisión del modelo: 0.8125
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.625
Puntaje F1 del modelo: 0.5846153846153846
Curva ROC - AUC del modelo: 0.625

#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 2)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=6 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=7 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=8 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=9 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=11 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=12 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)

Optimum number of features: 2
Score with 2 features: 0.677954
Index(['CSA%', 'Consultas'], dtype='object')

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=13 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

       CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[4 1]
 [2 2]]
Precisión del modelo: 0.6666666666666666
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.65
Puntaje F1 del modelo: 0.6493506493506493
Curva ROC - AUC del modelo: 0.6500000000000001

##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

       CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[4 1]
 [2 2]]
Precisión del modelo: 0.6666666666666666
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.65
Puntaje F1 del modelo: 0.6493506493506493
Curva ROC - AUC del modelo: 0.6500000000000001

##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

       CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[4 1]
 [2 2]]
Precisión del modelo: 0.6666666666666666
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.65
Puntaje F1 del modelo: 0.6493506493506493
Curva ROC - AUC del modelo: 0.6500000000000001

##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['CSA%', 'Consultas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

       CSA%  Consultas
0  0.000682   0.656096

In [ ]:
Y.head(2)

0    4
1    3
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob', reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[4 1]
 [2 2]]
Precisión del modelo: 0.6666666666666666
Exactitud del modelo: 0.6666666666666666
Sensibilidad del modelo: 0.65
Puntaje F1 del modelo: 0.6493506493506493
Curva ROC - AUC del modelo: 0.6500000000000001