In [ ]:
!pip uninstall scikit-learn
!pip install scikit-learn==0.24.2

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-1.0.2.dist-info/*
    /usr/local/lib/python3.7/dist-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-1.0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting scikit-learn==0.24.2
  Downloading scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
     |████████████████████████████████| 22.3 MB 1.4 MB/s
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.1.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (1.21.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn==0.24.2) (3.1.0)
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
Successfully installed scikit-learn-0.24.2

##Preprocesamiento - Data

##Data

In [ ]:
#Descargar excel desde link de Drive
!gdown --id text

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_excel("Data-Osiptel.xlsx", sheet_name="Claro")
data.head(5)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Reclamos,Bajas,Consultas,Altas
0,1,9,15.12,18518.00,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6390,0.6217,0.6588,0.7507
1,1,10,26.37,18591.50,0.001418,37908.0,506790.0,0.0748,123382.0,3391270.0,0.0364,0.7334,0.6642,0.6597,0.6445
2,1,11,3.58,18637.25,0.000192,37922.0,508222.0,0.0746,117383.0,3246056.0,0.0362,0.7112,0.6466,0.6270,0.6292
3,1,12,0.62,21049.75,0.000029,39301.0,518982.0,0.0757,11756.0,3382625.0,0.0348,0.7378,0.6847,0.6490,0.6697
4,1,1,0.83,19743.50,0.000042,35969.0,506900.0,0.0710,100277.0,3505628.0,0.0286,0.7641,0.7229,0.7189,0.7044

In [ ]:
#IMPUTACION
from sklearn.impute import SimpleImputer
simple = SimpleImputer().fit(data)
df_imputed = simple.transform(data)
df_imputed = pd.DataFrame(df_imputed, columns=data.columns)
data = df_imputed
data

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Reclamos,Bajas,Consultas,Altas
0,1.0,9.0,15.120000,18518.000000,0.000817,41584.000000,493360.000000,0.084300,118385.0,3.124089e+06,0.037900,0.639000,0.621700,0.658800,0.750700
1,1.0,10.0,26.370000,18591.500000,0.001418,37908.000000,506790.000000,0.074800,123382.0,3.391270e+06,0.036400,0.733400,0.664200,0.659700,0.644500
2,1.0,11.0,3.580000,18637.250000,0.000192,37922.000000,508222.000000,0.074600,117383.0,3.246056e+06,0.036200,0.711200,0.646600,0.627000,0.629200
3,1.0,12.0,0.620000,21049.750000,0.000029,39301.000000,518982.000000,0.075700,11756.0,3.382625e+06,0.034800,0.737800,0.684700,0.649000,0.669700
4,1.0,1.0,0.830000,19743.500000,0.000042,35969.000000,506900.000000,0.071000,100277.0,3.505628e+06,0.028600,0.764100,0.722900,0.718900,0.704400
5,1.0,2.0,8.250000,18530.500000,0.000445,26550.000000,475277.000000,0.055900,61818.0,3.461584e+06,0.017900,0.797000,0.756500,0.769300,0.763000
6,1.0,3.0,1.520000,20930.750000,0.000073,25004.000000,488132.000000,0.051200,74489.0,3.694472e+06,0.020200,0.787200,0.745900,0.753800,0.760600
7,1.0,4.0,3.700000,19992.250000,0.000185,17778.000000,446492.000000,0.039800,56881.0,3.471795e+06,0.016400,0.808400,0.778200,0.795600,0.794100
8,1.0,5.0,0.000000,20780.250000,0.000000,18789.000000,434213.000000,0.043300,49189.0,3.527899e+06,0.013900,0.789900,0.773300,0.764100,0.776400
9,1.0,6.0,8.693953,21205.813953,0.000407,21373.534884,474994.116279,0.044985,34783.0,2.940542e+06,0.011901,0.793083,0.783137,0.787693,0.795267
10,1.0,7.0,7.180000,20583.750000,0.000349,16714.000000,441291.000000,0.037900,28800.0,3.239626e+06,0.008900,0.813900,0.787500,0.801200,0.783800
11,1.0,8.0,0.680000,20698.500000,0.000033,16631.000000,409005.000000,0.040700,26790.0,3.368573e+06,0.008000,0.792700,0.775400,0.778900,0.757400
12,2.0,9.0,13.070000,20791.000000,0.000629,16614.000000,447039.000000,0.037165,28200.0,3.274924e+06,0.008611,0.836672,0.826782,0.836964,0.846483
13,2.0,10.0,2.650000,20590.250000,0.000129,18120.000000,444409.000000,0.040773,30046.0,3.394403e+06,0.008852,0.804647,0.817908,0.800867,0.832273
14,2.0,11.0,1.840000,20453.750000,0.000090,20186.000000,448584.000000,0.044999,27794.0,3.094064e+06,0.008983,0.787831,0.786775,0.785283,0.810680
15,2.0,12.0,11.570000,21970.500000,0.000527,24565.000000,487204.000000,0.050420,32331.0,3.188555e+06,0.010140,0.762627,0.755562,0.738456,0.767059
16,2.0,1.0,0.170000,20970.500000,0.000008,21151.000000,463831.000000,0.045601,31975.0,3.083228e+06,0.010371,0.793281,0.760857,0.768052,0.783197
17,2.0,2.0,0.000000,20395.250000,0.000000,25670.000000,461846.000000,0.055581,28301.0,2.914392e+06,0.009711,0.710258,0.713331,0.699163,0.732027
18,2.0,3.0,4.800000,21421.500000,0.000224,25090.000000,475539.000000,0.052761,31074.0,2.962227e+06,0.010490,0.731498,0.741151,0.714904,0.748095
19,2.0,4.0,1.100000,21398.500000,0.000051,21751.000000,475211.000000,0.045771,40603.0,2.851686e+06,0.014238,0.762041,0.761276,0.733510,0.762037
20,2.0,5.0,13.370000,22022.250000,0.000607,20427.000000,520146.000000,0.039272,27667.0,2.909221e+06,0.009510,0.790722,0.772420,0.779957,0.791650
21,2.0,6.0,1.460000,21349.000000,0.000068,15697.000000,482379.000000,0.032541,23314.0,2.866739e+06,0.008133,0.834782,0.815070,0.840692,0.829706
22,2.0,7.0,3.420000,21862.750000,0.000156,15550.000000,466933.000000,0.033302,28001.0,2.941578e+06,0.009519,0.796516,0.797125,0.830571,0.808054
23,2.0,8.0,82.260000,22484.750000,0.003658,17163.000000,488156.000000,0.035159,45691.0,3.178351e+06,0.014376,0.773877,0.777521,0.810283,0.792835
24,3.0,9.0,16.140000,22370.000000,0.000722,18669.000000,649167.000000,0.034000,44135.0,3.057234e+06,0.014400,0.763500,0.758200,0.803100,0.778400
25,3.0,10.0,7.900000,22196.000000,0.000356,19539.000000,507969.000000,0.038500,32328.0,2.764541e+06,0.011700,0.816100,0.817500,0.837400,0.837500
26,3.0,11.0,13.250000,21568.500000,0.000614,16667.000000,504509.000000,0.033000,28163.0,2.708331e+06,0.010400,0.857000,0.852800,0.876700,0.870600
27,3.0,12.0,29.320000,22253.500000,0.001318,23895.000000,518464.000000,0.046100,25228.0,2.666419e+06,0.009500,0.798800,0.790900,0.821900,0.798500
28,3.0,1.0,13.540000,22408.500000,0.000604,21331.000000,521947.000000,0.040900,21419.0,2.925380e+06,0.007300,0.830000,0.821400,0.855800,0.835700
29,3.0,2.0,13.580000,20480.000000,0.000663,19271.000000,465185.000000,0.041400,19006.0,2.721997e+06,0.007000,0.836900,0.827700,0.851700,0.825400
30,3.0,3.0,15.680000,22764.500000,0.000689,17657.000000,544011.000000,0.032500,17873.0,2.831259e+06,0.006300,0.873200,0.874100,0.885500,0.879100
31,3.0,4.0,11.170000,20895.000000,0.000535,15561.000000,476504.000000,0.032700,13984.0,2.489875e+06,0.005600,0.883900,0.882100,0.896700,0.895400
32,3.0,5.0,12.280000,22374.000000,0.000549,21938.000000,535544.000000,0.041000,20078.0,2.643379e+06,0.007600,0.827600,0.834900,0.845900,0.840500
33,3.0,6.0,2.970000,21577.250000,0.000138,22934.000000,471505.000000,0.048600,13129.0,2.638914e+06,0.005000,0.806100,0.808200,0.824300,0.831600
34,3.0,7.0,3.600000,21868.500000,0.000165,19952.000000,458687.000000,0.043500,11814.0,2.568330e+06,0.004600,0.790200,0.795500,0.789700,0.799700
35,3.0,8.0,3.150000,22655.000000,0.000139,16681.000000,461356.000000,0.036200,11236.0,2.663202e+06,0.004200,0.792100,0.800800,0.790200,0.806600
36,4.0,9.0,1.000000,22135.000000,0.000050,13066.000000,451604.000000,0.028900,11106.0,2.576963e+06,0.004300,0.827000,0.839800,0.820500,0.844700
37,4.0,10.0,9.530000,22462.250000,0.000420,12246.000000,445719.000000,0.027500,11093.0,2.648754e+06,0.004200,0.836100,0.833200,0.840300,0.862700
38,4.0,11.0,5.670000,22134.000000,0.000260,12479.000000,438504.000000,0.028500,11550.0,2.579743e+06,0.004500,0.850600,0.854200,0.857600,0.866300
39,4.0,12.0,5.280000,22413.500000,0.000240,19828.000000,444416.000000,0.044600,12860.0,2.597373e+06,0.005000,0.775200,0.783900,0.758200,0.766000
40,4.0,1.0,1.200000,22276.000000,0.000050,20021.000000,428153.000000,0.046800,12344.0,2.733556e+06,0.004500,0.788100,0.796300,0.782700,0.801500
41,4.0,2.0,1.380000,20137.000000,0.000070,17928.000000,384087.000000,0.046700,11576.0,2.544368e+06,0.004500,0.796500,0.803600,0.779200,0.824600
42,4.0,3.0,2.070000,21792.500000,0.000090,17781.000000,411650.000000,0.043200,11564.0,2.551255e+06,0.004500,0.785100,0.783800,0.801800,0.833600
43,4.0,4.0,1.570000,21323.000000,0.000100,15484.000000,415825.000000,0.037200,11036.0,1.459441e+06,0.004500,0.809200,0.833300,0.836600,0.860200

In [ ]:
data["Reclamos"]

0     0.639000
1     0.733400
2     0.711200
3     0.737800
4     0.764100
5     0.797000
6     0.787200
7     0.808400
8     0.789900
9     0.793083
10    0.813900
11    0.792700
12    0.836672
13    0.804647
14    0.787831
15    0.762627
16    0.793281
17    0.710258
18    0.731498
19    0.762041
20    0.790722
21    0.834782
22    0.796516
23    0.773877
24    0.763500
25    0.816100
26    0.857000
27    0.798800
28    0.830000
29    0.836900
30    0.873200
31    0.883900
32    0.827600
33    0.806100
34    0.790200
35    0.792100
36    0.827000
37    0.836100
38    0.850600
39    0.775200
40    0.788100
41    0.796500
42    0.785100
43    0.809200
Name: Reclamos, dtype: float64

In [ ]:
bins = [0.00, 0.20, 0.40, 0.60, 0.80, 1.0]
names = ["1", "2", "3", "4", "5"]

In [ ]:
data["Reclamos-Cat"] = pd.cut(data["Reclamos"], bins, labels = names)
data[["Reclamos", "Reclamos-Cat"]].head(5)

   Reclamos Reclamos-Cat
0    0.6390            4
1    0.7334            4
2    0.7112            4
3    0.7378            4
4    0.7641            4

In [ ]:
data = data.drop(['Reclamos'], axis=1)
data.head(5)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas,Reclamos-Cat
0,1.0,9.0,15.12,18518.00,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6217,0.6588,0.7507,4
1,1.0,10.0,26.37,18591.50,0.001418,37908.0,506790.0,0.0748,123382.0,3391270.0,0.0364,0.6642,0.6597,0.6445,4
2,1.0,11.0,3.58,18637.25,0.000192,37922.0,508222.0,0.0746,117383.0,3246056.0,0.0362,0.6466,0.6270,0.6292,4
3,1.0,12.0,0.62,21049.75,0.000029,39301.0,518982.0,0.0757,11756.0,3382625.0,0.0348,0.6847,0.6490,0.6697,4
4,1.0,1.0,0.83,19743.50,0.000042,35969.0,506900.0,0.0710,100277.0,3505628.0,0.0286,0.7229,0.7189,0.7044,4

In [ ]:
data["Reclamos-Cat"].value_counts().sort_index()

1     0
2     0
3     0
4    27
5    17
Name: Reclamos-Cat, dtype: int64

#XGboost - Shrinkage (alpha - lambda)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,15.12,18518.0,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,15.12,18518.0,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,15.12,18518.0,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier()

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,AÑO,Mes,N° de horas sin sistema de atención al mes,N° total de horas de atención al mes,CSA%,Nº DE USUARIOS QUE DESISTIERON DE LA ATENCIÓN AL MES,Nº TOTAL DE USUARIOS ATENDIDOS AL MES,DAP (%),Nº DE LLAMADAS NO FINALIZADAS POR EL USUARIO,Nº TOTAL DE LLAMADAS ATENDIDAS,CAT (%),Bajas,Consultas,Altas
0,1.0,9.0,15.12,18518.0,0.000817,41584.0,493360.0,0.0843,118385.0,3124089.0,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

#XGboost - Con RFE

##RFE

In [ ]:
from sklearn import linear_model
from time import time
import numpy as np
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = data.dropna()
X = df.drop(['Reclamos-Cat'], axis=1)
Y = df['Reclamos-Cat']

#######################################
#no of features
nof_list=np.arange(1,14)            
high_score=0
#Variable to store the optimum features
nof=0           
score_list =[]
for n in range(len(nof_list)):
    X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    rfe = RFE(model,nof_list[n])
    X_train_rfe = rfe.fit_transform(X_train,y_train)
    X_test_rfe = rfe.transform(X_test)
    model.fit(X_train_rfe,y_train)
    score = model.score(X_test_rfe,y_test)
    score_list.append(score)
    if(score>high_score):
        high_score = score
        nof = nof_list[n]
print("Optimum number of features: %d" %nof)
print("Score with %d features: %f" % (nof, high_score))
#########################################
cols = list(X.columns)
model = LinearRegression()
#Initializing RFE model
rfe = RFE(model, 8)             
#Transforming data using RFE
X_rfe = rfe.fit_transform(X,Y)  
#Fitting the data to model
model.fit(X_rfe,Y)              
temp = pd.Series(rfe.support_,index = cols)
selected_features_rfe = temp[temp==True].index
print(selected_features_rfe)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Optimum number of features: 8
Score with 8 features: 0.438011
Index(['Mes', 'N° de horas sin sistema de atención al mes  ', 'CSA%',
       'DAP (%)', 'CAT (%)', 'Bajas', 'Consultas', 'Altas'],
      dtype='object')

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=1 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=3 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=6 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=7 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=8 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=9 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=11 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=12 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=13 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=8 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)

##XGBoost - Solo

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,Mes,N° de horas sin sistema de atención al mes,CSA%,DAP (%),CAT (%),Bajas,Consultas,Altas
0,9.0,15.12,0.000817,0.0843,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Lasso

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,Mes,N° de horas sin sistema de atención al mes,CSA%,DAP (%),CAT (%),Bajas,Consultas,Altas
0,9.0,15.12,0.000817,0.0843,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=0)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1, reg_lambda=0)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Ridge

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,Mes,N° de horas sin sistema de atención al mes,CSA%,DAP (%),CAT (%),Bajas,Consultas,Altas
0,9.0,15.12,0.000817,0.0843,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=0, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier()

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333

##XGBoost - Elasticnet

In [ ]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = data.dropna()

In [ ]:
X = df[['Mes',
        'N° de horas sin sistema de atención al mes  ',
        'CSA%',
        'DAP (%)',
        'CAT (%)',
        'Bajas',
        'Consultas',
        'Altas']]
Y = df['Reclamos-Cat']

In [ ]:
X.head(1)

,Mes,N° de horas sin sistema de atención al mes,CSA%,DAP (%),CAT (%),Bajas,Consultas,Altas
0,9.0,15.12,0.000817,0.0843,0.0379,0.6217,0.6588,0.7507

In [ ]:
Y.head(2)

0    4
1    4
Name: Reclamos-Cat, dtype: category
Categories (5, object): ['1' < '2' < '3' < '4' < '5']

In [ ]:
seed = 7
test_size = 0.2
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

In [ ]:
model = XGBClassifier(reg_alpha=1, reg_lambda=1)
model.fit(X_train, y_train)

XGBClassifier(reg_alpha=1)

In [ ]:
from sklearn import metrics
from sklearn.metrics import *

#Realizo la predicción
y_pred = model.predict(X_test)
#Verifico la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
#Calculo la precisión del modelo
precision = precision_score(y_test, y_pred, average="macro")
#Calculo la exactitud del modelo
exactitud = accuracy_score(y_test, y_pred)
#Calculo la sensibilidad del modelo
sensibilidad = recall_score(y_test, y_pred, average="macro")
#Calculo el Puntaje F1 del modelo
puntajef1 = f1_score(y_test, y_pred, average="macro")
#Calculo la curva ROC - AUC del modelo
roc_auc = roc_auc_score(y_test, y_pred)

print('Matriz de Confusión:')
print(matriz)
print('Precisión del modelo:', precision)
print('Exactitud del modelo:', exactitud)
print('Sensibilidad del modelo:', sensibilidad)
print('Puntaje F1 del modelo:', puntajef1)
print('Curva ROC - AUC del modelo:', roc_auc)

Matriz de Confusión:
[[6 0]
 [1 2]]
Precisión del modelo: 0.9285714285714286
Exactitud del modelo: 0.8888888888888888
Sensibilidad del modelo: 0.8333333333333333
Puntaje F1 del modelo: 0.8615384615384616
Curva ROC - AUC del modelo: 0.8333333333333333